### ISSUE TITLE
`getTitleToken` does not work { doSisuAuth: false, authTitle: Titles.MinecraftJava, deviceType: "Win32" }

### ISSUE THREAD

**Issue by AlphaBs** [PrismarineJS/prismarine-auth#54]
- [x] The [readme](https://github.com/PrismarineJS/prismarine-auth/README.md) doesn't contain a resolution to my issue 
- [x] The [example](https://github.com/PrismarineJS/prismarine-auth/example.js) doesn't contain a resolution to my issue 

## Versions
 - node: 17.7.2
 - prismarine-auth: 1.7.0

## Detailed description of a problem
When I set `doSisuAuth` to false and set `authTitle` to MinecraftJava, It always returns an error: 403 Forbidden

![image](https://user-images.githubusercontent.com/17783561/186713679-71deb095-d8e4-4be6-b4de-64368b4410eb.png)

## Your current code
```js
const { Authflow, Titles } = require('prismarine-auth')

module.exports = doAuth = async (id,cache) => {
    // not work
    const flow = new Authflow(id,cache, { doSisuAuth: false, authTitle: Titles.MinecraftJava, deviceType: 'Win32' })
    const response = await flow.getXboxToken()
    console.log(response)
}
```
(from /examples/xbox/sisu.js)

## Expected behavior
return tokens without error

## Additional context
I found `getTitleToken` function always failed to request. [XboxTokenManager.js](https://github.com/PrismarineJS/prismarine-auth/blob/07992e090cbf3f6e98561953512a576732a0e864/src/TokenManagers/XboxTokenManager.js#L258)

I also tried another options and it works fine:
```js
const flow = new Authflow(id,cache, { doSisuAuth: false, authTitle: Titles.MinecraftNintendoSwitch, deviceType: 'Nintendo' })
```

Isn't it allowed to request title authentication with Titles.MinecraftJava?

---

**Comment by extremeheat** [comment]
Why are you setting this flag? What tokens are you seeking?

**Comment by LucienHH** [comment]
Just to chime in as well `/examples/xbox/sisu.js` has `doSisuAuth` set to true as it is needed for the Java titleId

**Comment by AlphaBs** [comment]
I want to make a minecraft client that allows accounts under the age of 18 to log in and uses my azure app id. 
but `doSisuAuth` does not work for my azure app id: [docs](https://github.com/PrismarineJS/prismarine-auth/blob/07992e090cbf3f6e98561953512a576732a0e864/docs/API.md?plain=1#L128)

my real code looks like this:

```js
const flow = new Authflow(id,cache, { doSisuAuth: false, authTitle: "<my-azure-app-id>", deviceType: 'Win32' })
const msaToken = loginWithMsalJs() // i used MSAL.js

// flow.xbl.getUserToken
// flow.xbl.getDeviceToken
// flow.xblgetTitleToken
// flow.xbl.getXSTSToken
// flow.mca.getAccessToken
```

can I do like this?

**Comment by LucienHH** [comment]
Currently, custom Azure apps aren't really supported in prismarine-auth due to some scopes not being set correctly, we'd also need to account for the fact that the majority of custom Azure apps are unable to create title tokens. We could add a flag like `customAzureApp: true` to the options because I'm not sure how else we'd be able to distinguish.

**Comment by extremeheat** [comment]
The Windows app IDs and the Azure app IDs have different length (latter in UUID form) so that can be used to disambiguate. And yes, the privileges of an azure app usually means that full authentication cannot happen for XBL APIs. There is little reason to use them in favor of the current Minecraft* tokens unless you need it for some production thing. In which case we could use a PR. The only practical difference to the user is what the sign-in page lists as the app you sign in to..

**Comment by LucienHH** [comment]
Azure apps also have Window app ids as well and can be substituted in and out, I think it'd be very rare to see someone use a custom Azure app with the Window app ID but it does exist. I think it would be a useful addition as I'm sure there are a few people who use pauth just for XBL authentication and would find use in it.
